name: Pull Request Tests

on:
  pull_request:
    branches:
      - master
      - main
      - develop
      - ci_cd_with_github_runner_and_grafana  # Testing branch
    paths:
      - '**.m'
      - '**.slx'
      - 'test/**'
      - '.github/workflows/pr-tests.yml'

  # Allow manual trigger
  workflow_dispatch:

# Add permissions for the workflow to write comments to PRs
permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  test-single-vehicle:
    name: Single Vehicle Tests
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: R2025a

      - name: Run Single Vehicle Tests
        id: single_vehicle_tests
        uses: matlab-actions/run-command@v2
        continue-on-error: true
        with:
          command: |
            cd('test/single_veh_test');
            run_all_single_test;

      - name: Upload Single Vehicle Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: pr-${{ github.event.pull_request.number }}-single-vehicle-results
          path: test/single_veh_test/results/
          retention-days: 14

      - name: Send logs to Grafana Loki
        if: always()
        env:
          LOKI_URL: ${{ secrets.GRAFANA_LOKI_URL }}
          LOKI_USER: ${{ secrets.GRAFANA_LOKI_USERNAME }}
          LOKI_KEY: ${{ secrets.GRAFANA_LOKI_API_KEY }}
        shell: bash
        run: |
          # Only send logs if Grafana Loki is configured
          if [ -z "$LOKI_URL" ]; then
            echo "Grafana Loki not configured, skipping logs"
            exit 0
          fi

          # Get current timestamp in nanoseconds
          TIMESTAMP=$(date +%s%N)

          # Create log message
          MESSAGE="Test completed: single-vehicle tests ${{ steps.single_vehicle_tests.outcome }}"

          # Create Loki push payload
          cat <<EOF | curl -X POST "$LOKI_URL" \
            -u "$LOKI_USER:$LOKI_KEY" \
            -H "Content-Type: application/json" \
            --data-binary @- || echo "Failed to send logs to Grafana Loki"
          {
            "streams": [
              {
                "stream": {
                  "job": "github-actions",
                  "workflow": "pr-tests",
                  "test_type": "single-vehicle",
                  "repository": "${{ github.repository }}",
                  "branch": "${{ github.head_ref || github.ref_name }}",
                  "event": "${{ github.event_name }}",
                  "status": "${{ steps.single_vehicle_tests.outcome }}"
                },
                "values": [
                  ["$TIMESTAMP", "$MESSAGE"]
                ]
              }
            ]
          }
          EOF

      - name: Comment PR with results
        if: always() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const resultPath = 'test/single_veh_test/results';
            let comment = '## Single Vehicle Test Results\n\n';

            if ('${{ job.status }}' === 'success') {
              comment += ':white_check_mark: Tests passed successfully!\n\n';
            } else {
              comment += ':x: Tests failed!\n\n';
            }

            comment += 'Download the full test report from the workflow artifacts.\n';

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });

  test-multi-vehicle:
    name: Multi Vehicle Tests
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: R2025a

      - name: Run Multi Vehicle Tests
        id: multi_vehicle_tests
        uses: matlab-actions/run-command@v2
        continue-on-error: true
        with:
          command: |
            cd('test/multi_veh_test');
            run_all_multi_test;

      - name: Upload Multi Vehicle Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: pr-${{ github.event.pull_request.number }}-multi-vehicle-results
          path: test/multi_veh_test/results/
          retention-days: 14

      - name: Send logs to Grafana Loki
        if: always()
        env:
          LOKI_URL: ${{ secrets.GRAFANA_LOKI_URL }}
          LOKI_USER: ${{ secrets.GRAFANA_LOKI_USERNAME }}
          LOKI_KEY: ${{ secrets.GRAFANA_LOKI_API_KEY }}
        shell: bash
        run: |
          # Only send logs if Grafana Loki is configured
          if [ -z "$LOKI_URL" ]; then
            echo "Grafana Loki not configured, skipping logs"
            exit 0
          fi

          # Get current timestamp in nanoseconds
          TIMESTAMP=$(date +%s%N)

          # Create log message
          MESSAGE="Test completed: multi-vehicle tests ${{ steps.multi_vehicle_tests.outcome }}"

          # Create Loki push payload
          cat <<EOF | curl -X POST "$LOKI_URL" \
            -u "$LOKI_USER:$LOKI_KEY" \
            -H "Content-Type: application/json" \
            --data-binary @- || echo "Failed to send logs to Grafana Loki"
          {
            "streams": [
              {
                "stream": {
                  "job": "github-actions",
                  "workflow": "pr-tests",
                  "test_type": "multi-vehicle",
                  "repository": "${{ github.repository }}",
                  "branch": "${{ github.head_ref || github.ref_name }}",
                  "event": "${{ github.event_name }}",
                  "status": "${{ steps.multi_vehicle_tests.outcome }}"
                },
                "values": [
                  ["$TIMESTAMP", "$MESSAGE"]
                ]
              }
            ]
          }
          EOF

      - name: Comment PR with results
        if: always() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const resultPath = 'test/multi_veh_test/results';
            let comment = '## Multi Vehicle Test Results\n\n';

            if ('${{ job.status }}' === 'success') {
              comment += ':white_check_mark: Tests passed successfully!\n\n';
            } else {
              comment += ':x: Tests failed!\n\n';
            }

            comment += 'Download the full test report from the workflow artifacts.\n';

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });

  pr-summary:
    name: PR Test Summary
    needs: [test-single-vehicle, test-multi-vehicle]
    runs-on: ubuntu-latest
    if: always() && github.event_name == 'pull_request'

    steps:
      - name: Post overall summary
        uses: actions/github-script@v7
        with:
          script: |
            const singleVehicle = '${{ needs.test-single-vehicle.result }}';
            const multiVehicle = '${{ needs.test-multi-vehicle.result }}';

            let summary = '## Test Suite Summary\n\n';
            summary += '| Test Suite | Status |\n';
            summary += '|------------|--------|\n';
            summary += `| Single Vehicle | ${singleVehicle === 'success' ? ':white_check_mark: Passed' : ':x: Failed'} |\n`;
            summary += `| Multi Vehicle | ${multiVehicle === 'success' ? ':white_check_mark: Passed' : ':x: Failed'} |\n\n`;

            if (singleVehicle === 'success' && multiVehicle === 'success') {
              summary += ':tada: All tests passed! This PR is ready for review.\n';
            } else {
              summary += ':warning: Some tests failed. Please review the test reports in the workflow artifacts.\n';
            }

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: summary
            });

      - name: Set PR status
        run: |
          if [ "${{ needs.test-single-vehicle.result }}" == "success" ] && [ "${{ needs.test-multi-vehicle.result }}" == "success" ]; then
            echo "All tests passed!"
            exit 0
          else
            echo "Some tests failed!"
            exit 1
          fi
